export const ADD_NOTE = 'ADD_NOTE';
export const ARCHIVE_NOTE = 'ARCHIVE_NOTE';
export const PIN_NOTE = 'PIN_NOTE';
export const SET_SEARCHED_NOTES = 'SET_SEARCHED_NOTES';
export const DELETE_NOTE = 'DELETE_NOTE';
export const EDIT_NOTE = 'EDIT_NOTE';
export const CHANGE_NOTE_COLOR = 'CHANGE_NOTE_COLOR';
export const TOGGLE_CHECKLIST = 'TOGGLE_CHECKLIST';
export const RESTORE_NOTE = 'RESTORE_NOTE';




export const NEW_SAVE_NOTES_REQUEST = 'NEW_SAVE_NOTES_REQUEST'
export const NEW_SAVE_NOTES_SUCCESS = 'NEW_SAVE_NOTES_UCCESS'
export const NEW_SAVE_NOTES_FAIL = 'NEW_SAVE_NOTES_FAIL'


export const ALL_NOTES_REQUEST = 'ALL_NOTES_REQUEST'
export const ALL_NOTES_FAIL = 'ALL_NOTES_FAIL'
export const ALL_NOTES_SUCCESS= 'ALL_NOTES_SUCCESS'

export const ALL_BIN_REQUEST = 'ALL_BIN_REQUEST'
export const ALL_BIN_FAIL = 'ALL_BIN_FAIL'
export const ALL_BIN_SUCCESS= 'ALL_BIN_SUCCESS'

export const NOTE_DETAILS_REQUEST = 'NOTE_DETAILS_REQUEST'
export const NOTE_DETAILS_SUCCESS = 'NOTE_DETAILS_UCCESS'
export const NOTE_DETAILS_FAIL = 'NOTE_DETAILS_FAIL'

export const DELETE_NOTE_REQUEST = 'DELETE_NOTE_REQUEST'
export const  DELETE_NOTE_SUCCESS= 'DELETE_NOTE_SUCCESS'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
export const CLEAR_NOTES = 'CLEAR_NOTES'